### ISSUE TITLE
"/list" command occasionally fails with "[ErrorResponseException] 10062: Unknown interaction"

### ISSUE THREAD

**Issue by unilock** [fooooooooooooooo/VelocityDiscord#26]
Sometimes, after executing the `/list` command in Discord, the following is printed to the Velocity logs:

```
[09:55:54] [Netty epoll Worker #4/WARN] [ooo.foooooooooooo.velocitydiscord.VelocityDiscord]: Could not ping server: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /127.0.0.1:30010
[09:55:54] [ForkJoinPool.commonPool-worker-42/ERROR] [velocitydiscord.net.dv8tion.jda.api.requests.RestAction]: RestAction queue returned failure: [ErrorResponseException] 10062: Unknown interaction
velocitydiscord.net.dv8tion.jda.api.exceptions.ContextException: null
	at velocitydiscord.net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54) ~[?:?]
	at velocitydiscord.net.dv8tion.jda.api.requests.Request.<init>(Request.java:73) ~[?:?]
	at velocitydiscord.net.dv8tion.jda.internal.requests.RestActionImpl.queue(RestActionImpl.java:200) ~[?:?]
	at velocitydiscord.net.dv8tion.jda.internal.requests.restaction.interactions.InteractionCallbackImpl.queue(InteractionCallbackImpl.java:74) ~[?:?]
	at velocitydiscord.net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:572) ~[?:?]
	at velocitydiscord.net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:538) ~[?:?]
	at ooo.foooooooooooo.velocitydiscord.discord.commands.ListCommand.handle(ListCommand.java:85) ~[?:?]
	at ooo.foooooooooooo.velocitydiscord.discord.Discord.onSlashCommandInteraction(Discord.java:255) ~[?:?]
	at velocitydiscord.net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:424) ~[?:?]
	at velocitydiscord.net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96) ~[?:?]
	at velocitydiscord.net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88) ~[?:?]
	at velocitydiscord.net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70) ~[?:?]
	at velocitydiscord.net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:173) ~[?:?]
	at velocitydiscord.net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleCommand(InteractionCreateHandler.java:112) ~[?:?]
	at velocitydiscord.net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleInternally(InteractionCreateHandler.java:83) ~[?:?]
	at velocitydiscord.net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:39) ~[?:?]
	at velocitydiscord.net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:965) ~[?:?]
	at velocitydiscord.net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:851) ~[?:?]
	at velocitydiscord.net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:829) ~[?:?]
	at velocitydiscord.net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1004) ~[?:?]
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385) ~[?:?]
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276) ~[?:?]
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996) ~[?:?]
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755) ~[?:?]
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) ~[?:?]
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) ~[?:?]
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[?:?]
```

...followed by the bot sending "<bot name> is thinking...", eventually replacing that with "The application did not respond" (after 15 minutes, probably).

I assume this is because not all backend servers can be pinged within 3 seconds, so Discord throws a fit and stops the bot from responding to the interaction.

I imagine deferring the reply to the command (using `deferredReply()`) would fix the issue.
(i'd open a pull request myself but don't have the time right now, sorry!)

**Comment by unilock** [comment]
Nevermind; my own Velocity / Discord plugin was breaking stuff, probably because it's poorly written. Oops.
