### ISSUE TITLE
Support for empty (null) messages

### ISSUE THREAD

**Issue by cosmicdan** [fooooooooooooooo/VelocityDiscord#33]
Thanks for the plugin, very simple and easy to setup :)

Currently wishing one feature though - to not send any messages on join/leave/etc.

I have achieved this by setting empty values....
```
join_message = ""
leave_message = ""
disconnect_message = ""
server_switch_message = ""
```
...but then the Velocity console will log a stacktrace every time these events happen, which is a little annoying...
```
[13:47:59 ERROR]: Couldn't pass ServerConnectedEvent to discord
java.lang.IllegalStateException: Cannot build empty messages! Must provide at least one of: content, embed, file, or stickers
	at velocitydiscord.net.dv8tion.jda.internal.requests.restaction.MessageCreateActionImpl.finalizeData(MessageCreateActionImpl.java:80) ~[?:?]
	at velocitydiscord.net.dv8tion.jda.internal.requests.RestActionImpl.queue(RestActionImpl.java:193) ~[?:?]
	at velocitydiscord.net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:572) ~[?:?]
	at velocitydiscord.net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:538) ~[?:?]
	at ooo.foooooooooooo.velocitydiscord.discord.Discord.sendMessage(Discord.java:197) ~[?:?]
	at ooo.foooooooooooo.velocitydiscord.discord.Discord.onConnect(Discord.java:173) ~[?:?]
	at ooo.foooooooooooo.velocitydiscord.discord.Lmbda$13.execute(Unknown Source) ~[?:?]
	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.2.0.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity-3.2.0.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity-3.2.0.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

...apart from that it works fine, doesn't crash or break so it's not a major issue otherwise :)

Ty!

**Comment by fooooooooooooooo** [comment]
i will add the ability to disable messages

**Comment by fooooooooooooooo** [comment]
added in 7e28b6af10a48f11cb118ffc8ec094c22335dac9
