### ISSUE TITLE
Couldn't pass DisconnectEvent to discord

### ISSUE THREAD

**Issue by tomkimberlin** [fooooooooooooooo/VelocityDiscord#35]
Getting the following error when shutting down Velocity (Velocity 3.2.0-SNAPSHOT):

```
[19:38:05 ERROR]: Couldn't pass DisconnectEvent to discord
java.util.concurrent.RejectedExecutionException: The Requester has been stopped! No new requests can be requested!
        at net.dv8tion.jda.internal.requests.Requester.request(Requester.java:109) ~[?:?]
        at net.dv8tion.jda.internal.requests.RestActionImpl.queue(RestActionImpl.java:200) ~[?:?]
        at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:572) ~[?:?]
        at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:538) ~[?:?]
        at ooo.foooooooooooo.velocitydiscord.discord.Discord.sendMessage(Discord.java:203) ~[?:?]
        at ooo.foooooooooooo.velocitydiscord.discord.Discord.onDisconnect(Discord.java:196) ~[?:?]
        at ooo.foooooooooooo.velocitydiscord.discord.Lmbda$29.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.2.0-SNAPSHOT-270.jar:3.2.0-SNAPSHOT (git-9be0bca3-b270)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity-3.2.0-SNAPSHOT-270.jar:3.2.0-SNAPSHOT (git-9be0bca3-b270)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity-3.2.0-SNAPSHOT-270.jar:3.2.0-SNAPSHOT (git-9be0bca3-b270)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[19:38:05 ERROR]: Couldn't pass DisconnectEvent to discord
java.util.concurrent.RejectedExecutionException: The Requester has been stopped! No new requests can be requested!
        at net.dv8tion.jda.internal.requests.Requester.request(Requester.java:109) ~[?:?]
        at net.dv8tion.jda.internal.requests.RestActionImpl.queue(RestActionImpl.java:200) ~[?:?]
        at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:572) ~[?:?]
        at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:538) ~[?:?]
        at ooo.foooooooooooo.velocitydiscord.discord.Discord.sendMessage(Discord.java:203) ~[?:?]
        at ooo.foooooooooooo.velocitydiscord.discord.Discord.onDisconnect(Discord.java:196) ~[?:?]
        at ooo.foooooooooooo.velocitydiscord.discord.Lmbda$29.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.2.0-SNAPSHOT-270.jar:3.2.0-SNAPSHOT (git-9be0bca3-b270)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity-3.2.0-SNAPSHOT-270.jar:3.2.0-SNAPSHOT (git-9be0bca3-b270)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity-3.2.0-SNAPSHOT-270.jar:3.2.0-SNAPSHOT (git-9be0bca3-b270)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
```

**Comment by fooooooooooooooo** [comment]
i think i forgot to tell discord jda to shut down before killing it, this should be a relatively harmless error but ill fix it soon

**Comment by fooooooooooooooo** [comment]
done in [a81f101](https://github.com/fooooooooooooooo/VelocityDiscord/commit/a81f10184aeb1fbe2367b1d78f859e0bc6bc8234)
