### ISSUE TITLE
Vmessage/VelocityDiscord

### ISSUE THREAD

**Issue by Kriptiq** [fooooooooooooooo/VelocityDiscord#55]
Hi, I was wondering about compatability with Vmessage plugin for cross server messaging. I get these errors (ServerPostConnectEven/PlayerChatEvent) on server join/switching or when sending in game messages.

29.08 03:22:00 [Server] INFO Kriptiq -> lobby has connected
29.08 03:22:01 [Server] INFO [, 7, 4 Kriptiq , ejoined , 7Lobby]
29.08 03:22:01 [Server] INFO Kriptiq joined Lobby
29.08 03:22:01 [Server] ERROR Couldn't pass ServerPostConnectEvent to vmessage 1.6.2
29.08 03:22:01 [Server] INFO java.lang.IllegalAccessError: class me.feusalamander.vmessage.Listeners tried to access private method 'void ooo.foooooooooooo.velocitydiscord.discord.Discord.sendMessage(java.lang.String)' (me.feusalamander.vmessage.Listeners is in unnamed module of loader com.velocitypowered.proxy.plugin.PluginClassLoader @2b214b94; ooo.foooooooooooo.velocitydiscord.discord.Discord is in unnamed module of loader com.velocitypowered.proxy.plugin.PluginClassLoader @319854f0)
29.08 03:22:01 [Server] INFO at me.feusalamander.vmessage.Listeners.onChange(Listeners.java:280) ~[?:?]
29.08 03:22:01 [Server] INFO at me.feusalamander.vmessage.Lmbda$74.execute(Unknown Source) ~[?:?]
29.08 03:22:01 [Server] INFO at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[custom-java21.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
29.08 03:22:01 [Server] INFO at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[custom-java21.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
29.08 03:22:01 [Server] INFO at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[custom-java21.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
29.08 03:22:01 [Server] INFO at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
29.08 03:22:01 [Server] INFO at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
29.08 03:22:01 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
29.08 03:22:10 [Server] INFO This command does not exist.
29.08 03:22:19 [Server] INFO Kriptiq -> create has connected
29.08 03:22:19 [Server] INFO Kriptiq -> lobby has disconnected
29.08 03:22:19 [Server] INFO [, 7, 4 Kriptiq , eleft , clobby , eto join , aCreate]
29.08 03:22:19 [Server] INFO Kriptiq left lobby to join Create
29.08 03:22:19 [Server] ERROR Couldn't pass ServerPostConnectEvent to vmessage 1.6.2
29.08 03:22:19 [Server] INFO java.lang.IllegalAccessError: class me.feusalamander.vmessage.Listeners tried to access private method 'void ooo.foooooooooooo.velocitydiscord.discord.Discord.sendMessage(java.lang.String)' (me.feusalamander.vmessage.Listeners is in unnamed module of loader com.velocitypowered.proxy.plugin.PluginClassLoader @2b214b94; ooo.foooooooooooo.velocitydiscord.discord.Discord is in unnamed module of loader com.velocitypowered.proxy.plugin.PluginClassLoader @319854f0)
29.08 03:22:19 [Server] INFO at me.feusalamander.vmessage.Listeners.onChange(Listeners.java:231) ~[?:?]
29.08 03:22:19 [Server] INFO at me.feusalamander.vmessage.Lmbda$74.execute(Unknown Source) ~[?:?]
29.08 03:22:19 [Server] INFO at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[custom-java21.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
29.08 03:22:19 [Server] INFO at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[custom-java21.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
29.08 03:22:19 [Server] INFO at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[custom-java21.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
29.08 03:22:19 [Server] INFO at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
29.08 03:22:19 [Server] INFO at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
29.08 03:22:19 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
29.08 03:25:36 [Server] INFO [, a(Create) , 4 Kriptiq , 8, l> , r#message#]
29.08 03:25:36 [Server] ERROR Couldn't pass PlayerChatEvent to vmessage 1.6.2
29.08 03:25:36 [Server] INFO java.lang.IllegalAccessError: class me.feusalamander.vmessage.Listeners tried to access private method 'void ooo.foooooooooooo.velocitydiscord.discord.Discord.sendMessage(java.lang.String)' (me.feusalamander.vmessage.Listeners is in unnamed module of loader com.velocitypowered.proxy.plugin.PluginClassLoader @2b214b94; ooo.foooooooooooo.velocitydiscord.discord.Discord is in unnamed module of loader com.velocitypowered.proxy.plugin.PluginClassLoader @319854f0)
29.08 03:25:36 [Server] INFO at me.feusalamander.vmessage.Listeners.lambda$message$0(Listeners.java:359) ~[?:?]
29.08 03:25:36 [Server] INFO at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[custom-java21.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
29.08 03:25:36 [Server] INFO at me.feusalamander.vmessage.Listeners.message(Listeners.java:356) ~[?:?]
29.08 03:25:36 [Server] INFO at me.feusalamander.vmessage.Listeners.onMessage(Listeners.java:50) ~[?:?]
29.08 03:25:36 [Server] INFO at me.feusalamander.vmessage.Lmbda$73.execute(Unknown Source) ~[?:?]
29.08 03:25:36 [Server] INFO at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[custom-java21.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
29.08 03:25:36 [Server] INFO at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[custom-java21.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
29.08 03:25:36 [Server] INFO at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[custom-java21.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
29.08 03:25:36 [Server] INFO at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
29.08 03:25:36 [Server] INFO at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
29.08 03:25:36 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]

![Screenshot_2](https://github.com/user-attachments/assets/68ac4dff-d3a4-401e-a840-1e982bb82cfe)
![Screenshot_3](https://github.com/user-attachments/assets/2c8ee4bf-8d25-4b6e-b755-3101fb90094c)

**Comment by fooooooooooooooo** [comment]
looking at the source of vmessage, this line seems to be using an internal method of velocitydiscord that was changed in a recent version 
https://github.com/FeuSalamander/Vmessage/blob/main/src/main/java/me/feusalamander/vmessage/Listeners.java#L280

this release should work until vmessage is updated with the changes to velocitydiscord 
https://github.com/fooooooooooooooo/VelocityDiscord/releases/tag/1.8.2

but given that the method is now private, i might need to make it public or expose a more public api
`java.lang.IllegalAccessError: class me.feusalamander.vmessage.Listeners tried to access private method 'void ooo.foooooooooooo.velocitydiscord.discord.Discord.sendMessage(java.lang.String)'`
