### ISSUE TITLE
[Bug] `/list` command fails if a backend server cannot be pinged

### ISSUE THREAD

**Issue by unilock** [fooooooooooooooo/VelocityDiscord#7]
In my Velocity config, I have a test server defined that I'm not always running.
If the `/list` command fails to ping a server, it dies on an exception.
```
[12:16:09] [JDA MainWS-ReadThread/ERROR]: One of the EventListeners had an uncaught exception
java.lang.RuntimeException: java.util.concurrent.ExecutionException: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /127.0.0.1:44444
	at ooo.foooooooooooo.velocitydiscord.discord.commands.ListCommand.handle(ListCommand.java:36) ~[?:?]
	at ooo.foooooooooooo.velocitydiscord.discord.Discord.onSlashCommandInteraction(Discord.java:187) ~[?:?]
	at velocitydiscord.net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:382) ~[?:?]
	at velocitydiscord.net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96) ~[?:?]
	at velocitydiscord.net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88) ~[?:?]
	at velocitydiscord.net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70) ~[?:?]
	at velocitydiscord.net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:170) ~[?:?]
	at velocitydiscord.net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleCommand(InteractionCreateHandler.java:109) ~[?:?]
	at velocitydiscord.net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleInternally(InteractionCreateHandler.java:80) ~[?:?]
	at velocitydiscord.net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:39) ~[?:?]
	at velocitydiscord.net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:953) ~[?:?]
	at velocitydiscord.net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:840) ~[?:?]
	at velocitydiscord.net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:818) ~[?:?]
	at velocitydiscord.net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:992) ~[?:?]
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385) ~[?:?]
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276) ~[?:?]
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996) ~[?:?]
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755) ~[?:?]
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) ~[?:?]
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) ~[?:?]
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[?:?]
Caused by: java.util.concurrent.ExecutionException: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /127.0.0.1:44444
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at ooo.foooooooooooo.velocitydiscord.discord.commands.ListCommand.handle(ListCommand.java:33) ~[?:?]
	... 20 more
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /127.0.0.1:44444
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
	at io.netty.channel.unix.Errors.newConnectException0(Errors.java:155) ~[velocity-3.1.2-SNAPSHOT-175.jar:3.1.2-SNAPSHOT (git-4b33d5fb-b175)]
	at io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:128) ~[velocity-3.1.2-SNAPSHOT-175.jar:3.1.2-SNAPSHOT (git-4b33d5fb-b175)]
	at io.netty.channel.unix.Socket.finishConnect(Socket.java:321) ~[velocity-3.1.2-SNAPSHOT-175.jar:3.1.2-SNAPSHOT (git-4b33d5fb-b175)]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:710) ~[velocity-3.1.2-SNAPSHOT-175.jar:3.1.2-SNAPSHOT (git-4b33d5fb-b175)]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:687) ~[velocity-3.1.2-SNAPSHOT-175.jar:3.1.2-SNAPSHOT (git-4b33d5fb-b175)]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:567) ~[velocity-3.1.2-SNAPSHOT-175.jar:3.1.2-SNAPSHOT (git-4b33d5fb-b175)]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:477) ~[velocity-3.1.2-SNAPSHOT-175.jar:3.1.2-SNAPSHOT (git-4b33d5fb-b175)]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385) ~[velocity-3.1.2-SNAPSHOT-175.jar:3.1.2-SNAPSHOT (git-4b33d5fb-b175)]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[velocity-3.1.2-SNAPSHOT-175.jar:3.1.2-SNAPSHOT (git-4b33d5fb-b175)]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.1.2-SNAPSHOT-175.jar:3.1.2-SNAPSHOT (git-4b33d5fb-b175)]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.1.2-SNAPSHOT-175.jar:3.1.2-SNAPSHOT (git-4b33d5fb-b175)]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```
I propose that servers defined in Velocity's config that cannot be pinged be present in the `/list` command with something like "Server cannot be reached" in place of the player list.

**Comment by fooooooooooooooo** [comment]
I couldnt find a way to get the servers max players without pinging the server, I didnt look that hard for a better solution though

**Comment by unilock** [comment]
Maybe if the server ping fails, just print the server name without the (max) player count?
```
[server1 2/20]
- player1
- player2

[server2 0/20]
No players online

[server3]
Server cannot be reached
```
Though this would require some code refactoring, I imagine, as well as changing the list formatting variables in the config file...

**Comment by fooooooooooooooo** [comment]
could just show "??" instead of the max player count if the ping fails, the other info isn't from the ping
the best solution would be to find another way of getting max users

**Comment by unilock** [comment]
Hm. I don't think there's any way to get the max player count without reading it directly from the `server.properties` of the backend server, which sounds like a bad idea (arbitrary filesystem access = attack surface).
Unless you cache it? But that would require the server to be online at least once, and would only work if the `/list` command was run while the server was online - unless you cache it whenever a player connects to said server, rather than when the `/list` command is run.
But, that might introduce some unnecessary overhead, considering the max player count doesn't update very often...
